title: WilL
logo: /assets/img/w.gif
description: Docs de <a title="Ir a perfil de Linkedin"href="https://www.linkedin.com/in/willeonardo/">WilL</a> y otros temas.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
